### ISSUE TITLE
Add option to attach feedback as a message attachment instead of additional channel messages

### ISSUE THREAD

**Issue by paultyng** [davidcelis/sparkles#6]
**Is your feature request related to a problem? Please describe.**

To avoid too much message noise, it'd be nice to optionally attach the confirmation of sparkles to the original message instead of creating a new message from the bot.

**Describe the solution you'd like**

See https://api.slack.com/messaging/composing/layouts#building-attachments

But basically, adding an attachment to any message that is triggering sparkles.

**Describe alternatives you've considered**

The existing method of providing an additional message can be noisy, but is a fine alternative, so maybe this is optional behavior?

**Additional context**

n/a

**Comment by davidcelis** [comment]
@paultyng I really like this idea and had actually planned to do something like this early on, but I couldn't really figure out how to do it 😓 Originally, I was planning on using the `response_url` to confirm a sparkle being given, but… Well, from [the docs](https://api.slack.com/interactivity/handling#updating_message_response): 

> You cannot use `replace_original` to modify the user-posted message that invokes a [slash command](https://api.slack.com/interactivity/slash-commands).

I agree it would be a lot cleaner to attach the confirmation to that original message but this made it seem like there's no way to modify the original message and show it, which is why I have the bot post a follow-up method. Is there maybe something I'm missing that would make this possible in another way?

**Comment by paultyng** [comment]
I think you can just update the message using `chat.update` instead of the hook response?

**Comment by davidcelis** [comment]
@paultyng My understanding is that `chat.update` can't be used to update a user's message, even when using a bot token…

**Comment by paultyng** [comment]
I though for adding attachments its ok. This is a very common use case for bots, to add attachments to messages (like custom unfurls, but that is maybe a different event/webhook). 

I just checked how the Jira bot does this when you mention a ticket (without tagging the bot or anything) and it looks like it just threads a reply to it:

![image](https://user-images.githubusercontent.com/422474/141698051-4b184934-a495-4652-a2af-118f906b1882.png)

**Comment by davidcelis** [comment]
Oh threading the reply would probably be a very easy and reasonable change to make!
